package_assets: on
package_path: assets-compiled
compress_assets: on
javascript_compressor: closure
gzip_assets: true

javascripts:
  application:
    # - public/javascripts/libraries/bootstrap.js
    # - public/javascripts/templates/**/*.jst
    - public/javascripts/application.js
  show:
    - public/javascripts/libraries/underscore.js
    - public/javascripts/libraries/backbone.js
    - public/javascripts/application.js
    - public/javascripts/dispatcher.js
    - public/javascripts/loadVideos.js
    - public/javascripts/videos.js
    - public/javascripts/player.js
  create:
    - public/javascripts/libraries/parsley.js
  jquery:
    - public/javascripts/libraries/jquery-1.9.1.js


stylesheets:
  application:
    - public/stylesheets/**/*.css
