development:
  sessions:
    default:
      database: unagi_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: unagi_test
      hosts:
        - localhost:27017
