development:
  sessions:
    default:
      database: unagi_development
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        skip_version_check: true
        safe: true
test:
  sessions:
    default:
      database: unagi_test
      hosts:
        - localhost:27017
